---
baseURL: "/"
languageCode: "en-us"
title: "Replicated Help Center"
theme: "replicated-docs-theme"
description: "Kube is a professional  and a responsive Hugo theme for developers and designers that offers a documentation section mixed with a landing page and a blog"
Paginate: 4
Params:
  RSSLink: "/index.xml"
  author: "newpixcom" # add your company name
  github: "" # add your github profile name
  twitter: "" # add your twitter profile
  email: "myemail@myaddress.xxx"

taxonomies:
  - category: "categories"

algolia:
  index: "help_center"
  key: "0038e146bfecd33072d241b4b7c33279"
  appID: "5PHVQPX4AR"

menu:
  main:
    - Name: "Guides"
      Weight: -100
      URL: "/guides/"
    - Name: "Documentation"
      Weight: -100
      URL: "/docs/"
    - Name: "API Reference"
      Weight: -100
      URL: "/api-reference/"
---
