---
baseURL: "/"
languageCode: "en-us"
title: "Kube for Hugo"
theme: "kube"
description: "Kube is a professional  and a responsive Hugo theme for developers and designers that offers a documentation section mixed with a landing page and a blog"
Paginate: 4
Params:
  RSSLink: "/index.xml"
  author: "newpixcom" # add your company name
  github: "" # add your github profile name
  twitter: "" # add your twitter profile
  email: "myemail@myaddress.xxx"

algolia:
  index: "help_center"
  key: "0038e146bfecd33072d241b4b7c33279"
  appID: "5PHVQPX4AR"

menu:
  main:
    - Name: "Docs"
      Weight: -100
      URL: "/docs/"
    - Name: "Blog"
      Weight: -100
      URL: "/blog/"
    - Name: "Faq"
      Weight: -100
      URL: "/faq/"
---
